theme: minima
title: ğŸ’• Midouzha's Personal Website
description: è®°å½•ç”Ÿæ´»çš„ç¾å¥½ç¬é—´ï¼Œä¸“å±äºZçš„æ¸©æš–å°å±‹ âœ¨
author: midouzha
email: your-email@example.com
baseurl: "" # å¦‚æœä½ çš„ç«™ç‚¹åœ¨å­ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®è¿™ä¸ªå€¼
url: "https://midouzha.github.io/skills-github-pages" # ä½ çš„ç«™ç‚¹URL

# ç¤¾äº¤åª’ä½“é“¾æ¥
github_username: midouzha
# twitter_username: your_twitter
# linkedin_username: your_linkedin

# ç½‘ç«™è®¾ç½®
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# åŒ…å«æ–‡ä»¶
include:
  - assets

# åˆ†é¡µè®¾ç½®
paginate: 5
paginate_path: "/page:num/"

# Markdown è®¾ç½®
markdown: kramdown
highlighter: rouge

# æ„å»ºè®¾ç½®
safe: true
incremental: false
